language: elixir
elixir:
- 1.4.0
dist: trusty
sudo: false
otp_release:
- 19.2
services:
- postgresql
addons:
  postgresql: 9.6
before_script:
- cp config/test.exs.travis config/test.exs
- MIX_ENV=test mix deps.get
- MIX_ENV=test mix ecto.create
script: "MIX_ENV=test mix coveralls.travis"
after_script:
- mix deps.get --only docs
- MIX_ENV=docs mix inch.report