language: elixir
elixir:
- 1.4.0
dist: trusty
sudo: false
otp_release:
- 19.2
services:
- postgresql
addons:
  postgresql: 9.6
before_script:
- cp config/test.exs.travis config/test.exs
- MIX_ENV=test mix ecto.create
- MIX_ENV=test mix ecto.migrate
- MIX_ENV=test mix run priv/repo/seeds.exs
script: "MIX_ENV=test mix do deps.get, test"
after_success:
  - "MIX_ENV=test mix compile && mix coveralls.travis"